"""empty message

Revision ID: 151ac76664c9
Revises: 
Create Date: 2023-03-05 11:14:31.300045

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '151ac76664c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('guid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('updated_by', postgresql.UUID(as_uuid=True), nullable=False),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_test_guid'), 'test', ['guid'], unique=True)
    op.create_table('user',
    sa.Column('guid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_user_guid'), 'user', ['guid'], unique=True)
    op.create_table('question',
    sa.Column('guid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('test_guid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('updated_by', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['test_guid'], ['test.guid'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_question_guid'), 'question', ['guid'], unique=True)
    op.create_index(op.f('ix_question_test_guid'), 'question', ['test_guid'], unique=False)
    op.create_table('answer',
    sa.Column('guid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('question_guid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('sub_text', sa.String(), nullable=True),
    sa.Column('is_correct', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('updated_by', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['question_guid'], ['question.guid'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_answer_guid'), 'answer', ['guid'], unique=True)
    op.create_index(op.f('ix_answer_question_guid'), 'answer', ['question_guid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answer_question_guid'), table_name='answer')
    op.drop_index(op.f('ix_answer_guid'), table_name='answer')
    op.drop_table('answer')
    op.drop_index(op.f('ix_question_test_guid'), table_name='question')
    op.drop_index(op.f('ix_question_guid'), table_name='question')
    op.drop_table('question')
    op.drop_index(op.f('ix_user_guid'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_test_guid'), table_name='test')
    op.drop_table('test')
    # ### end Alembic commands ###
